package unique

var tableTests = []struct {
	in  []string
	out []string
}{
	{[]string{"I love music.", "I love music.", "I love music.", " ", "I love music of Kartik.", "I love music of Kartik.",
		"Thanks.", "I love music of Kartik.", "I love music of Kartik."}, []string{"I love music.", " ", "I love music of Kartik.",
		"Thanks.", "I love music of Kartik."}},
	{[]string{"I love music.", "I love music.", "I love music.", " ", "I love music of Kartik.", "I love music of Kartik.",
		"Thanks.", "I love music of Kartik.", "I love music of Kartik."}, []string{"3 I love music.", "1  ", "2 I love music of Kartik.",
		"1 Thanks.", "2 I love music of Kartik."}},
	{[]string{"I love music.", "I love music.", "I love music.", " ", "I love music of Kartik.", "I love music of Kartik.",
		"Thanks.", "I love music of Kartik.", "I love music of Kartik."}, []string{"I love music.", "I love music of Kartik.", "I love music of Kartik."}},
	{[]string{"I love music.", "I love music.", "I love music.", " ", "I love music of Kartik.", "I love music of Kartik.",
		"Thanks.", "I love music of Kartik.", "I love music of Kartik."}, []string{" ", "Thanks."}},
	{[]string{"I LOVE MUSIC.", "I love music.", "I LoVe MuSiC.", " ", "I love MuSIC of Kartik.", "I love music of kartik.",
		"Thanks.", "I love music of kartik.", "I love MuSIC of Kartik."}, []string{"I LOVE MUSIC.", " ", "I love MuSIC of Kartik.", "Thanks.", "I love music of kartik."}},
	{[]string{"We love music.", "I love music.", "They love music.", " ", "I love music of Kartik.", "We love music of Kartik.",
		"Thanks."}, []string{"We love music.", " ", "I love music of Kartik.", "Thanks."}},
	{[]string{"I love music.", "A love music.", "C love music.", " ", "I love music of Kartik.", "We love music of Kartik.",
		"Thanks."}, []string{"I love music.", " ", "I love music of Kartik.", "We love music of Kartik.", "Thanks."}},
	{[]string{"Небо", "Небо", "Облако", "Облако", "Пляж", "Анапа",
		"Анапа"}, []string{"Небо", "Облако", "Пляж", "Анапа"}},
	{[]string{"Небо", "Небо", "Облако", "Облако", "Пляж", "Анапа",
		"Анапа"}, []string{"2 Небо", "2 Облако", "1 Пляж", "2 Анапа"}},
	{[]string{"Небо", "Небо", "Облако", "Облако", "Пляж", "Анапа",
		"Анапа"}, []string{"Небо", "Облако", "Анапа"}},
	{[]string{"Небо", "Небо", "Облако", "Облако", "Пляж", "Анапа",
		"Анапа"}, []string{"Пляж"}},
	{[]string{"Небо голуБое", "Небо голубое", "Облако Голубое", "Облако ГолУбое", "Пляж чистый", "Анапа солнечнаЯ",
		"Анапа солНечная", "Сторона СолНечная"}, []string{"Небо голуБое", "Пляж чистый", "Анапа солнечнаЯ"}},
	{[]string{"Небо голуБое", "Небо голубое", "Облако Голубое", "Облако ГолУбое", "Пляж чистый", "Анапа солнечнаЯ",
		"Анапа солНечная", "Сторона СолНечная"}, []string{"4 Небо голуБое", "1 Пляж чистый", "3 Анапа солнечнаЯ"}},
	{[]string{"Небо голуБое", "Небо голубое", "Облако Голубое", "Облако ГолУбое", "Пляж чистый", "Анапа солнечнаЯ",
		"Анапа солНечная", "Сторона СолНечная"}, []string{"Небо голуБое", "Анапа солнечнаЯ"}},
	{[]string{"Небо голуБое", "Небо голубое", "Облако Голубое", "Облако ГолУбое", "Пляж чистый", "Анапа солнечнаЯ",
		"Анапа солНечная", "Сторона СолНечная"}, []string{"Пляж чистый"}},
	{[]string{"Небо и голуБое", "Небо я голубое", "Облако Б Голубое", "Облако Q Голубое", "Пляж Я чистый", "Анапа т солнечнаЯ",
		"Анапа г солНечная", "Сторона ф СолНечная"}, []string{"Небо и голуБое", "Пляж Я чистый", "Анапа т солнечнаЯ"}},
	{[]string{"Небо и голуБое", "Небо я голубое", "Облако Б Голубое", "Облако А Голубое", "Пляж Я чистый", "Анапа т солнечнаЯ",
		"Анапа г солНечная", "Сторона ф СолНечная"}, []string{"4 Небо и голуБое", "1 Пляж Я чистый", "3 Анапа т солнечнаЯ"}},
	{[]string{"Небо и голуБое", "Небо я голубое", "Облако Б Голубое", "Облако Д Голубое", "Пляж Я чистый", "Анапа т солнечнаЯ",
		"Анапа г солНечная", "Сторона ф СолНечная"}, []string{"Небо и голуБое", "Анапа т солнечнаЯ"}},
	{[]string{"Небо и голуБое", "Небо я голубое", "Облако Б Голубое", "Облако Д Голубое", "Пляж Я чистый", "Анапа т солнечнаЯ",
		"Анапа г солНечная", "Сторона ф СолНечная"}, []string{"Пляж Я чистый"}},
}
